name: Deploy Next.js App

on:
  push:
    branches:
      - main   # adjust this if you use a different branch name for production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        node-version: '16'

    - name: SSH and deploy
      env:
        DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
        FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        HOST: irlab.uncg.edu
        USER: jggrandi
      run: |
        mkdir -p ~/.ssh/
        echo "$DEPLOY_SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan $HOST >> ~/.ssh/known_hosts
        
        # Here's where you SCP the app and handle deployment on the server.
        rsync -av --exclude '.git/' ./ $USER@$HOST:/home/jggrandi/projects/Theory-of-Computation-AI-TA
        
        ssh $USER@$HOST <<EOF
          cd /home/jggrandi/projects/Theory-of-Computation-AI-TA
          docker build --no-cache -t nextjs-app .
          docker stop nextjs-app-container
          docker rm nextjs-app-container
          docker run -d \
            --name nextjs-app-container \
            -p 3000:3000 \
            -e OPENAI_API_KEY=$OPENAI_API_KEY \
            -e FIREBASE_API_KEY=$FIREBASE_API_KEY \
            -e FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN \
            -e FIREBASE_APP_ID=$FIREBASE_APP_ID \
            -e FIREBASE_MEASUREMENT_ID=$FIREBASE_MEASUREMENT_ID \
            -e FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID \
            -e FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID \
            -e FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET \
            nextjs-app
        EOF

